### ISSUE TITLE
Hi, could you please provide the train.py and loss.py code?

### ISSUE THREAD

**Issue by strawberry1996** [jeffsonfu/DSAGAN#1]

**Comment by jeffsonfu** [comment]
Yes, the train.py and loss.py is uploaded in the attachment.
















At 2021-12-27 10:48:40, "strawberry邓泽宇" ***@***.***> wrote:

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
